# Configurações do Kafka
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.clientes=CLIENTES
kafka.consumer.group-id=crm-integration

# Configurações do CRM
crm.api.base-url=https://crm.com
crm.api.clients-endpoint=/api/v2/clientes

# Configurações de logging
logging.level.com.integration.kafka2crm=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Configurações de servidor
server.port=8080 